name: translate_service

services:
  translate-service:
    container_name: translate_service
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../:/app/
    env_file:
      - .env
    command: >
      uvicorn app.main:app 
      --host 0.0.0.0 
      --port 8000
      --reload
    tty: true
    networks:
      - robot_network

networks:
  robot_network:
    driver: bridge