name: translate_mBART_50

services:
  ros-humble-master: 
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../:/app/
    env_file:
      - ./.env
    ports:
      - "80:80/udp" 
    networks:
      - robot_network

networks:
  robot_network:
    driver: bridge